#----------------------------------*-sh-*--------------------------------------
# =========                 |
# \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
#  \\    /   O peration     |
#   \\  /    A nd           | Copyright (C) 1991-2009 OpenCFD Ltd.
#    \\/     M anipulation  |
#-------------------------------------------------------------------------------
# License
#     This file is part of OpenFOAM.
#
#     OpenFOAM is free software; you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by the
#     Free Software Foundation; either version 2 of the License, or (at your
#     option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM; if not, write to the Free Software Foundation,
#     Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
#
# Script
#     ensight/cshrc
#
# Description
#     Setup file for Ensight 8.?
#     Sourced from OpenFOAM-*/etc/cshrc
#
#------------------------------------------------------------------------------

# fallback value
if (! $?CEI_HOME) then
    setenv CEI_HOME /usr/local/ensight/CEI
endif

if ( -r $CEI_HOME ) then

    # special treatment for 32bit FOAM and 64bit Ensight
    if ($WM_ARCH == linux) then
        setenv CEI_ARCH linux_linux_2.6_32
    endif

    set path=($path $CEI_HOME/bin)

    setenv ENSIGHT8_INPUT dummy
    setenv ENSIGHT8_READER $FOAM_LIBBIN
else
    unsetenv CEI_HOME
endif

# -----------------------------------------------------------------------------
