#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application="mhdFoam"

(cd hartmann && runApplication blockMesh)
(cd hartmann && runApplication $application)
(cd hartmann && runApplication foamCalc components U)
(cd hartmann && runApplication sample)
