#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

if [ -d "$ParaView_DIR" -a -r "$ParaView_DIR" ]
then
   case "$ParaView_VERSION" in
   2*)
      wmake libso vtkFoam
      (
         cd PVFoamReader
         mkdir -p Make/$WM_OPTIONS > /dev/null 2>&1
         cd Make/$WM_OPTIONS
         cmake ../..
         make
      )
      ;;
   esac
fi

# ----------------------------------------------------------------- end-of-file
