#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

keepCases="moriyoshiHomogeneous"
loseCases="moriyoshiHomogeneousPart2"

for case in $keepCases
do
    (cd $case && foamCleanTutorials)
done

for case in $loseCases
do
    removeCase $case
done
