#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application="XiFoam"

setControlDict () {
    controlDict="system/controlDict"
    sed \
    -e s/"\(deltaT[ \t]*\) 5e-06;"/"\1 1e-05;"/g \
    -e s/"\(endTime[ \t]*\) 0.005;"/"\1 0.015;"/g \
    -e s/"\(writeInterval[ \t]*\) 10;"/"\1 50;"/g \
    $controlDict > temp.$$
    mv temp.$$ $controlDict
}

# Do moriyoshiHomogeneous
(cd moriyoshiHomogeneous && foamRunTutorials)

# Clone case
cloneCase moriyoshiHomogeneous moriyoshiHomogeneousPart2

# Modify and execute
cd moriyoshiHomogeneousPart2
    cp -r ../moriyoshiHomogeneous/0.005 .
    setControlDict
    runApplication $application
cd ..
