#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`

runApplication blockMesh

runApplication decomposePar

runParallel mdInitialise 4
runParallel $application 4

runApplication reconstructPar
