#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cd cylinder
    cleanCase
    rm -rf 0 > /dev/null 2>&1
    cp -r 0.org 0
    wclean analyticalCylinder
cd ..

cd pitzDaily
    cleanCase
    rm -rf 0 > /dev/null 2>&1
    cp -r 0.org 0
cd ..

