#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean
wclean interDyMFoam
wclean MRFInterFoam
wclean porousInterFoam

# ----------------------------------------------------------------- end-of-file
