#!/bin/sh
# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# remove old time folders
rm -rf 0 *[1-9]* processor* postProcessing

# copy 0.org to 0
cp -r 0.org 0

cleanCase

