#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# create mesh
runApplication blockMesh

# initialise with potentialFoam solution
runApplication potentialFoam
rm -f 0/phi

# run the solver
runApplication porousExplicitSourceReactingParcelFoam
