/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     |
    \\  /    A nd           | Copyright (C) 2008-2009 OpenCFD Ltd.
     \\/     M anipulation  |
-------------------------------------------------------------------------------
License
    This file is part of OpenFOAM.

    OpenFOAM is free software; you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by the
    Free Software Foundation; either version 2 of the License, or (at your
    option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM; if not, write to the Free Software Foundation,
    Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA

Class
    CoalCloud

Description

SourceFiles
    CoalCloud.C

\*---------------------------------------------------------------------------*/

#ifndef CoalCloud_H
#define CoalCloud_H

#include "ReactingMultiphaseCloud.H"
#include "CoalParcel.H"

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

namespace Foam
{

/*---------------------------------------------------------------------------*\
                          Class CoalCloud Declaration
\*---------------------------------------------------------------------------*/

template<class ThermoType>
class CoalCloud
:
    public ReactingMultiphaseCloud<CoalParcel<ThermoType> >
{
    // Private Member Functions

        //- Disallow default bitwise copy construct
        CoalCloud(const CoalCloud&);

        //- Disallow default bitwise assignment
        void operator=(const CoalCloud&);


public:

    //-Runtime type information
    TypeName("CoalCloud");


    // Constructors

        //- Construct given carrier gas fields
        CoalCloud
        (
            const word& cloudName,
            const volScalarField& rho,
            const volVectorField& U,
            const dimensionedVector& g,
            basicThermo& thermo
        );


    //- Destructor
    ~CoalCloud();


    // Member Functions

        //- Write fields
        virtual void writeFields() const;
};


// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

} // End namespace Foam

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#ifdef NoRepository
    #include "CoalCloud.C"
#endif

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#endif

// ************************************************************************* //
