#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

if [ -d "$ParaView_DIR" -a -r "$ParaView_DIR" ]
then
    case "$ParaView_VERSION" in
    3* | git)

        if [ ! "${PV_PLUGIN_PATH}" ]
        then
            echo "$0 : PV_PLUGIN_PATH not a valid directory."
            exit 1
        fi

        wmake libso vtkPV3Foam
        (
            cd PV3FoamReader
            mkdir -p Make/$WM_OPTIONS > /dev/null 2>&1
            cd Make/$WM_OPTIONS
            cmake ../..
            make
        )
        ;;
    esac
fi

# ----------------------------------------------------------------- end-of-file
