#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`

# create mesh
runApplication blockMesh

# create ignition cells cellSet
runApplication cellSet

runApplication $application
