#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf VTK
#rm -rf constant/cellToRegion constant/polyMesh/sets
rm -rf constant/polyMesh/sets
#rm -rf constant/cellLevel
#rm -rf constant/cellZones
#rm -rf constant/faceZones
#rm -rf constant/faces
#rm -rf constant/neighbour
#rm -rf constant/owner
#rm -rf constant/pointZones
#rm -rf constant/points
#rm -rf constant/refinementHistory
#rm -rf constant/surfaceIndex

# ----------------------------------------------------------------- end-of-file
