#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cd periodicCubeArgon
    rm -rf 0/*
    rm -f Ar-Ar
    rm -f electrostatic
    rm -f constant/idList
    rm -rf constant/polyMesh/sets
    cleanCase
cd ..

cd periodicCubeWater
    rm -rf 0/*
    rm -f O-O
    rm -f electrostatic
    rm -f constant/idList
    rm -rf constant/polyMesh/sets
    cleanCase
cd ..
