#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="mdEquilibrationFoam"

cd periodicCubeArgon
    runApplication blockMesh
    runApplication mdInitialise
    runApplication $application
cd ..

cd periodicCubeWater
    runApplication blockMesh
    runApplication mdInitialise
    runApplication $application
cd ..