#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

sensibleEnthalpyCombustionThermophysicalModels/Allwmake
wmake libso combustionModels
wmake

# ----------------------------------------------------------------- end-of-file
