#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean libso combustionModels
wclean all sensibleEnthalpyCombustionThermophysicalModels
wclean

# ----------------------------------------------------------------- end-of-file
