#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`

compileApplication ../../buoyantPisoFoam/hotRoom/setHotRoom
runApplication blockMesh
runApplication setHotRoom
runApplication $application
