#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication decomposePar
runParallel dsmcInitialise 4
runParallel dsmcFoam 4
runApplication reconstructPar -noLagrangian

