#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Generate the base block mesh
runApplication blockMesh

# Generate the snappy mesh
runApplication snappyHexMesh -overwrite

# Run the solver
runApplication interPhaseChangeFoam

