#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application="fireFoam"

runApplication blockMesh
runApplication setSet -batch makeFaceSet.setSet
runApplication createPatch -overwrite
runApplication decomposePar -force

# Run
runParallel $application 4

# -----------------------------------------------------------------------------
