#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

chmod a+rX $WM_PROJECT_DIR
chmod a+rX $WM_PROJECT_DIR/doc
chmod -R a+rX Doxygen

Doxygen/Allwmake

# ----------------------------------------------------------------- end-of-file
