#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

runApplication blockMesh
cp 0/alpha1.org 0/alpha1
cp 0/p.org 0/p
runApplication setFields
runApplication decomposePar
runParallel $application 4
runApplication reconstructPar
