#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake libso field
wmake libso forces
wmake libso IO
wmake libso utilities
wmake libso systemCall
wmake libso zones

# ----------------------------------------------------------------- end-of-file
