#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake libso turbulenceModel
wmake libso RAS
wmake libso LES

# ----------------------------------------------------------------- end-of-file
