#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication setSet -batch makeFaceSet.setSet
runApplication createPatch -overwrite

# Run
runApplication fireFoam

# -----------------------------------------------------------------------------
