#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cd throttle
    rm -rf constant/polyMesh/sets > /dev/null 2>&1
    rm -rf 0/polyMesh > /dev/null 2>&1
    rm system/cellSetDict > /dev/null 2>&1

    cleanCase
cd ..

cd throttle3D
    rm -rf constant/polyMesh/sets > /dev/null 2>&1
    rm -rf 0 > /dev/null 2>&1
    cp -r 0.org 0
    rm system/cellSetDict > /dev/null 2>&1
    rm -rf processor[0-9] > /dev/null 2>&1

    cleanCase
cd ..

