#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application="cavitatingFoam"

refineMeshByCellSet()
{
   while [ $# -ge 1 ]
   do
      echo "creating cell set for primary zone - $1"
      cp system/cellSetDict.$1 system/cellSetDict
      cellSet > log.cellSet.$1 2>&1

      echo "refining primary zone - $1"
      refineMesh -dict -overwrite > log.refineMesh.$1 2>&1
      shift
   done
}

cd throttle
    runApplication blockMesh
    refineMeshByCellSet 1 2 3
    runApplication $application
cd ..

cd throttle3D
    cp -r 0.org 0

    runApplication blockMesh
    refineMeshByCellSet 1 2 3

    echo "mapping fields from 2D throttle case"
    mapFields ../throttle -sourceTime latestTime >& log.mapFields

    runApplication decomposePar
    runParallel $application 4
    runApplication reconstructPar
cd ..

