#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

if [ -d "$ParaView_DIR" -a -r "$ParaView_DIR" ]
then
    case "$ParaView_VERSION" in
    3* | git)
        wmake libso vtkPV3Readers
        PV3FoamReader/Allwmake
    ;;
    esac
fi

# ----------------------------------------------------------------- end-of-file
