#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application="multiphaseInterFoam"

runApplication blockMesh
runApplication setFields
runApplication $application

