#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

keepCases="damBreak"
loseCases="damBreakFine"

for case in $keepCases
do
    (cd $case && foamCleanTutorials)

    if [ "$case" = "damBreak" ]
    then
        cp $case/0/alpha1.org $case/0/alpha1
    fi
done

for case in $loseCases
do
    removeCase $case
done
