#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake libso decompositionMethods

if [ -d "$FOAM_MPI_LIBBIN" ]
then
    (WM_OPTIONS=${WM_OPTIONS}$WM_MPLIB; wmake libso parMetisDecomp)
fi

# ----------------------------------------------------------------- end-of-file
