#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake libso decompositionMethods

wmake libso scotchDecomp
wmake libso metisDecomp

if [ -d "$FOAM_MPI_LIBBIN" ]
then
    WM_OPTIONS=${WM_OPTIONS}$WM_MPLIB
    wmake libso parMetisDecomp
fi

# ----------------------------------------------------------------- end-of-file
