#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake libso incompressible
wmake libso interfaceProperties
# wmake libso compressible

# ----------------------------------------------------------------- end-of-file
