#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication setSet -batch createObstacle.setSet
runApplication subsetMesh -overwrite c0 -patch walls
cp -r 0.org 0 > /dev/null 2>&1
runApplication setFields
runApplication interDyMFoam
