#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication setSet -batch createObstacle.setSet
runApplication subsetMesh c0 -patch walls
runApplication setFields
runApplication interDyMFoam
