#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake libo postCalc
wmake libso foamCalcFunctions

functionObjects/Allwmake

# ----------------------------------------------------------------- end-of-file
