#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmakeLnInclude ../incompressible/LES

wmake libso LESfilters
wmake libso LESdeltas

# ----------------------------------------------------------------- end-of-file
