#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

if [ "$PWD" != "$WM_PROJECT_DIR/src" ]
then
    echo "Error: Current directory in not \$WM_PROJECT_DIR/src"
    echo "    The environment variable are not consistent with the installation."
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
fi

set -x

# update OpenFOAM version strings if required
wmakePrintBuild -check || /bin/rm -f OpenFOAM/Make/$WM_OPTIONS/global.? 2>/dev/null

wmakeLnInclude OpenFOAM
wmakeLnInclude OSspecific/$WM_OSTYPE
Pstream/Allwmake

wmake libo  OSspecific/$WM_OSTYPE
wmake libso OpenFOAM

wmake libso lagrangian/basic

wmake libso triSurface
wmake libso edgeMesh
wmake libso surfMesh

# Decomposition methods needed by meshTools
decompositionMethods/Allwmake

wmake libso meshTools
wmake libso finiteVolume

wmake libso sampling

wmake libso dynamicMesh
wmake libso dynamicFvMesh
wmake libso topoChangerFvMesh

wmake libso ODE
wmake libso randomProcesses

thermophysicalModels/Allwmake
transportModels/Allwmake
turbulenceModels/Allwmake
lagrangian/Allwmake
postProcessing/Allwmake
conversion/Allwmake

wmake libso autoMesh
wmake libso errorEstimation

fvAgglomerationMethods/Allwmake

wmake libso fvMotionSolver
wmake libso engine

# ----------------------------------------------------------------- end-of-file
