#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake libso scotchDecomp
wmake libso metisDecomp
wmake libso parMetisDecomp
wmake libso MGridGen/MGridGen


# ----------------------------------------------------------------- end-of-file
