#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake libso metis/GKlib

wmake libso scotchDecomp

wmake libso metisDecomp

wmake libso parmetis/parmetis
wmake libso parmetis/metis-parmetis

wmake libso MGridGen/MGridGen


# ----------------------------------------------------------------- end-of-file
