#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

runApplication blockMesh
cp 0/alpha1.org 0/alpha1
cp 0/p_rgh.org 0/p_rgh
runApplication setFields
runApplication $application
